sudo: false
language: haskell
ghc:
    - 7.6
    - 7.8
env:
    - AWSBOUND=0.9.2
    - AWSBOUND=9
install:
    - cabal install --only-dependencies --enable-tests --constraint="aws<$AWSBOUND"
script:
    - cabal configure --enable-tests && cabal build

